version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Entered the install phase...
      - pip install pipenv
      - pipenv install
      - pipenv venv
      - source venv/bin/activate  
      - pip install flask
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python tests/test_sample.py
      - pipenv run python -m unittest # not an interactive session so we need to run
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
